### ISSUE TITLE
There is a bug about the command ".ob" and ".oblist"

### ISSUE THREAD

**Issue by GeraAxis** [w4123/Dice#11]
### At the beginning of I found the bug
I use a dicebot that build by the CDK (isn`t kokona). 
First, I use the command ".ob" then I use the command ".oblist". The bot didn't back info.
### Second times, 
we use kokona. 4 people of us use ".ob", then use ".oblist" ,it just could back a name 4 times. The name is the man who use the command first.
### Clear the bug plz!

**Comment by w4123** [comment]
Hi SX21H,

Thanks for your report and we have detected the source of the problem. We are currently working on it and will hopefully solve it in the next version. We will get back to you if we have any problems regarding with the bug.

Thanks for your support to the Dice! project.

Best regards,
w4123

**Comment by w4123** [comment]
Hi SX21H,

This bug has been fixed and we are very appreciated to your report for the bug. New version will be released as soon as possible.

Thanks for your support to the Dice! project.

Best regards,
w4123
