### ISSUE TITLE
搭建PDF中有一个明显的误导别人的错误

### ISSUE THREAD

**Issue by BobLiu0518** [w4123/Dice#15]
**搭建PDF中有一个明显的误导别人的错误**
![image](https://user-images.githubusercontent.com/24805093/48672325-7284c080-eb6f-11e8-85b5-39e099f457d1.png)
这句话。
酷Q Pro 是可以做到这一点的。
你要做的就是修改conf文件夹中的“CQP.cfg”，
如果有`[Dev]`标签，在其下方添加`Platform=2`；
如果没有，在文件末尾添加：
```
[Dev]
Platform=2
```
然后重启酷Q，就可以酷Q/电脑/手机同时在线。

**Comment by w4123** [comment]
我知道的其实
感谢反馈
