### ISSUE TITLE
关于.group ban指令可能触发程序崩溃

### ISSUE THREAD

**Issue by keet789** [w4123/Dice#36]
在尝试2.3.8Express7版本的时候发现一个bug：
群主输入.group ban random之后酷Q程序崩溃了。
![QQ图片20190628033025](https://user-images.githubusercontent.com/52318061/60337152-18df4280-9957-11e9-9dc3-9627dbe8bc8f.jpg)

PS.我完全不会编程，直接下载了发布的com.w4123.dice CPK文件之后放进酷Q app文件夹里。
Manual里列出的功能都可以正常使用。

最后感谢大佬提供的骰子！

**Comment by w4123** [comment]
感谢反馈，找时间看

**Comment by w4123** [comment]
已经锁定并重现bug， @mystringEmpty修好直接提交到这个repo然后发布新版本
