### ISSUE TITLE
是否可以考虑作为hoshino bot的插件开发？

### ISSUE THREAD

**Issue by asdfghjkl68qq** [w4123/Dice#50]
https://github.com/Ice-Cirno/HoshinoBot，现有的使用量较大的pcr bot，基于python，如果dice有适配的插件版本的话可以使大量hoshino bot提供骰娘功能，降低转化难度

**Comment by w4123** [comment]
感谢你的建议，我们会认真考虑的，不过python这里适配可能会有些难度

**Comment by j1g5awi** [comment]
这里是一位朋友开发的作为 HoshinoBot 插件的 Dice! 移植 ：https://github.com/maxesisn/nonedice

这里是我开发的兼容 nonebot 基本框架（不兼容HoshinoBot）的 Dice! 移植：https://github.com/thereisnodice/nodice/

希望可以帮到你。
