### ISSUE TITLE
请问转义变量是否支持内部操作？

### ISSUE THREAD

**Issue by Lykeios** [w4123/Dice#56]
可否在配置文件json中对转义变量进行一些函数操作？比如：

 "strJrrp": "{nick}取得随机数: {res}，取反{-res}，绝对值{abs(res)}，开根{sqrt(res)}......"

翻阅了一下文档似乎没有提及，如果支持的话能否讲解一下具体用法

**Comment by w4123** [comment]
没有支持，欢迎pr
不过现有架构不太好写这个
