### ISSUE TITLE
微信版Dice开发

### ISSUE THREAD

**Issue by leochen-g** [w4123/Dice#58]
看到Dice这个掷骰功能，我非常感兴趣，而且社区也很活跃，有很多人都在贡献自己的牌堆。由于之前写过一些微信的机器人功能，所以准备把dice的部分功能移植到微信的环境中，做个微信版的Dice。用的是开源的wechaty，目前已经实现把dice的json牌组无缝添加进来，可以实现.draw 的功能，后续会逐渐完善功能。希望能和各位开发者多多交流  [表情]

同时声明 我做的这个微信版的也是开源的 功能根据dice的牌组格式进行兼容，是dice的一个扩展，和dice没有任何竞争关系，我也是看到dice的功能非常nice[表情] 所以想贡献一份力量  让一个牌组可以运行在两个环境中

开源地址： https://github.com/leochen-g/wechaty-dice-bot

下面是我目前的测试图：
![image](https://user-images.githubusercontent.com/20028566/132340552-d8b9448d-e080-42b3-aaa2-7e39cdf12874.png)
![image](https://user-images.githubusercontent.com/20028566/132340568-02492f35-e96c-4ae6-9c48-c307ef6c3f5f.png)

**Comment by w4123** [comment]
好的哦，多多关照
