### ISSUE TITLE
疑似2.6.2版本有bug

### ISSUE THREAD

**Issue by kevinluo6191** [w4123/Dice#61]
无法正常设置 识别人名 jrrp等信息
![QQ图片20220112163623](https://user-images.githubusercontent.com/96232844/149124748-d758e1da-5a5c-4900-a384-3dab09e00fba.jpg)
![QQ图片20220112183741](https://user-images.githubusercontent.com/96232844/149124757-3d0b0447-3367-4d1d-8cd8-0c55b46a433b.png)
![QQ图片20220112183751](https://user-images.githubusercontent.com/96232844/149124759-f27f828c-94a7-4454-b37d-bf1b1f4404a5.png)
![QQ图片20220112183821](https://user-images.githubusercontent.com/96232844/149124762-b51f793c-bde0-460f-ab46-7277e7181111.png)

**Comment by kevinluo6191** [comment]
@mystringEmpty

**Comment by mystringEmpty** [comment]
文本格式在GlobalVar.cpp，新版只是废弃了对两年前远古版本的兼容
